/*
 * ControlPalette.java
 *
 * Created on November 13, 2008, 7:49 PM
 */
package com.novusradix.JavaPop.Client;

import com.novusradix.JavaPop.Client.Tools.BaseTool;
import com.novusradix.JavaPop.Client.Tools.RaiseLowerTool;
import com.novusradix.JavaPop.Client.Tools.Tool;
import com.novusradix.JavaPop.Server.Player.PeonMode;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;

/**
 *
 * @author  mom
 */
public class ControlPalette extends javax.swing.JPanel {
    public Map<String, JPanel> tabs;
    public ToolButton defaultButton;
    
    /** Creates new form ControlPalette */
    public ControlPalette() {
        initComponents();
        BaseTool.InitControlPalette(this);
        tabs = new HashMap<String, JPanel>();
        setupButtons(BaseTool.getAllTools());
    }

    public void setDefaultTool() {
        defaultButton.setSelected(true);
    }

    private void setupButtons(Collection<Tool> tools)
    {
        for(Tool t:tools)
        {
            ToolButton b = new ToolButton(t);
            ToolGroup.add(b);
            if(!tabs.containsKey(t.getType())){
                JPanel tab = new JPanel();
                ToolTabs.add(t.getType(), tab);
                tabs.put(t.getType(), tab);
            }
            tabs.get(t.getType()).add(b);
         
            if(t.getClass() == RaiseLowerTool.class)
            {
                defaultButton = b;
                defaultButton.setSelected(true);
            }
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToolGroup = new javax.swing.ButtonGroup();
        BehaviourGroup = new javax.swing.ButtonGroup();
        ToolTabs = new javax.swing.JTabbedPane();
        BehaviourPanel = new javax.swing.JPanel();
        SettleButton = new javax.swing.JToggleButton();
        GoToAnkhButton = new javax.swing.JToggleButton();
        FightButton = new javax.swing.JToggleButton();
        GatherButton = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(128, 64));
        setMinimumSize(new java.awt.Dimension(128, 64));

        BehaviourGroup.add(SettleButton);
        SettleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/novusradix/JavaPop/icons/Settle.png"))); // NOI18N
        SettleButton.setSelected(true);
        SettleButton.setToolTipText("Settle");
        SettleButton.setPreferredSize(new java.awt.Dimension(64, 64));
        SettleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettleButtonActionPerformed(evt);
            }
        });
        BehaviourPanel.add(SettleButton);

        BehaviourGroup.add(GoToAnkhButton);
        GoToAnkhButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/novusradix/JavaPop/icons/GoToAnkh.png"))); // NOI18N
        GoToAnkhButton.setToolTipText("Go to Ankh");
        GoToAnkhButton.setPreferredSize(new java.awt.Dimension(64, 64));
        GoToAnkhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToAnkhButtonActionPerformed(evt);
            }
        });
        BehaviourPanel.add(GoToAnkhButton);

        BehaviourGroup.add(FightButton);
        FightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/novusradix/JavaPop/icons/Fight.png"))); // NOI18N
        FightButton.setToolTipText("Fight");
        FightButton.setPreferredSize(new java.awt.Dimension(64, 64));
        FightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FightButtonActionPerformed(evt);
            }
        });
        BehaviourPanel.add(FightButton);

        BehaviourGroup.add(GatherButton);
        GatherButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/novusradix/JavaPop/icons/Gather.png"))); // NOI18N
        GatherButton.setToolTipText("Gather");
        GatherButton.setPreferredSize(new java.awt.Dimension(64, 64));
        GatherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GatherButtonActionPerformed(evt);
            }
        });
        BehaviourPanel.add(GatherButton);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(BehaviourPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(ToolTabs, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(ToolTabs, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(BehaviourPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void SettleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettleButtonActionPerformed
    BaseTool.SetBehaviour(PeonMode.SETTLE);
}//GEN-LAST:event_SettleButtonActionPerformed

private void GoToAnkhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToAnkhButtonActionPerformed
    BaseTool.SetBehaviour(PeonMode.ANKH);
}//GEN-LAST:event_GoToAnkhButtonActionPerformed

private void FightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FightButtonActionPerformed
    BaseTool.SetBehaviour(PeonMode.FIGHT);
}//GEN-LAST:event_FightButtonActionPerformed

private void GatherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GatherButtonActionPerformed
    BaseTool.SetBehaviour(PeonMode.GROUP);
}//GEN-LAST:event_GatherButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BehaviourGroup;
    private javax.swing.JPanel BehaviourPanel;
    private javax.swing.JToggleButton FightButton;
    private javax.swing.JToggleButton GatherButton;
    private javax.swing.JToggleButton GoToAnkhButton;
    private javax.swing.JToggleButton SettleButton;
    private javax.swing.ButtonGroup ToolGroup;
    private javax.swing.JTabbedPane ToolTabs;
    // End of variables declaration//GEN-END:variables
}
