/*
 * MainWindow.java
 *
 * Created on January 17, 2009, 1:39 PM
 */
package javapoptools;

import com.sun.opengl.util.Animator;
import java.awt.Dimension;
import java.io.File;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.opengl.GLCapabilities;
import javax.swing.JFileChooser;

/**
 *
 * @author  mom
 */
public class MainWindow extends javax.swing.JFrame {

    MainPanel mp;
    final JFileChooser modelChooser = new JFileChooser();
    final JFileChooser textureChooser = new JFileChooser();

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();

        GLCapabilities caps = new GLCapabilities();
        caps.setSampleBuffers(true);
        caps.setNumSamples(8);
        mp = new MainPanel(caps);


        mp.setPreferredSize(new Dimension(128, 128));
        previewPanel.add(mp);

        XImporter i = new XImporter(getClass().getResource("/com/novusradix/JavaPop/models/peon5.x"));
        mp.setData(i.getModel());
        Animator a = new Animator(mp);
        a.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        previewPanel = new javax.swing.JPanel();
        Menu = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        OpenMenuItem = new javax.swing.JMenuItem();
        openTextureMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("JavaPop tools"); // NOI18N

        optionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jRadioButton1.setText("jRadioButton1");
        optionPanel.add(jRadioButton1);

        previewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview"));

        FileMenu.setText("File");

        OpenMenuItem.setText("Open Model...");
        OpenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(OpenMenuItem);

        openTextureMenuItem.setText("Open Texture...");
        openTextureMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTextureMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(openTextureMenuItem);

        Menu.add(FileMenu);

        jMenu2.setText("Edit");
        Menu.add(jMenu2);

        setJMenuBar(Menu);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(previewPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(optionPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 173, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(optionPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
            .add(previewPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void OpenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenMenuItemActionPerformed

    int returnVal = modelChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File f = modelChooser.getSelectedFile();
        XImporter i;
        try {
            i = new XImporter(f.toURL());
            mp.setData(i.getModel());
        } catch (MalformedURLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}//GEN-LAST:event_OpenMenuItemActionPerformed

private void openTextureMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTextureMenuItemActionPerformed
// TODO add your handling code here:
//GEN-LAST:event_openTextureMenuItemActionPerformed
    int returnVal = textureChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File f = textureChooser.getSelectedFile();
        try{
            mp.setTexture(f.toURL());
        } catch (MalformedURLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem OpenMenuItem;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JMenuItem openTextureMenuItem;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPanel previewPanel;
    // End of variables declaration//GEN-END:variables

}
