/*
 * MainWindow.java
 *
 * Created on January 17, 2009, 1:39 PM
 */
package javapoptools;

import com.sun.opengl.util.Animator;
import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.media.opengl.GLCapabilities;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;

/**
 *
 * @author  mom
 */
public class MainWindow extends javax.swing.JFrame {

    MainPanel mp;
    final JFileChooser modelChooser = new JFileChooser();
    final JFileChooser textureChooser = new JFileChooser();
    final TextEditorForm vertexShaderEditor, fragmentShaderEditor;
    Color playerColor=Color.RED;
    
    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
        vertexShaderEditor = new TextEditorForm();
        vertexShaderEditor.setTitle("Vertex Shader");
        fragmentShaderEditor = new TextEditorForm();
        fragmentShaderEditor.setTitle("Fragment Shader");
        
        
        GLCapabilities caps = new GLCapabilities();
        caps.setSampleBuffers(true);
        caps.setNumSamples(8);
        mp = new MainPanel(caps, this);


        mp.setPreferredSize(new Dimension(128, 128));
        previewPanel.add(mp);

        XImporter i = new XImporter(getClass().getResource("/com/novusradix/JavaPop/models/peon5.x"));
        mp.setData(i.getModel());
        Animator a = new Animator(mp);
        a.start();
    }

    public void setVertexStatus(String s)
    {
        vertexShaderEditor.setStatus(s);
    }

    public void setFragmentStatus(String s){
        fragmentShaderEditor.setStatus(s);
    }
      
    public void appendVertexStatus(String s)
    {
        vertexShaderEditor.appendStatus(s);
    }

    public void appendFragmentStatus(String s){
        fragmentShaderEditor.appendStatus(s);
    }
    
    public String getVertexShader()
    {
        return vertexShaderEditor.getText();
    }
    
    public String getFragmentShader()
    {
        return fragmentShaderEditor.getText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        ShaderButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        previewPanel = new javax.swing.JPanel();
        Menu = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        OpenMenuItem = new javax.swing.JMenuItem();
        openTextureMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("JavaPop tools"); // NOI18N

        optionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jLabel1.setText("Zoom");

        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(4);
        jSlider1.setMinimum(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(1);
        jSlider1.setPreferredSize(new java.awt.Dimension(170, 54));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        ShaderButton.setText("Edit shaders");
        ShaderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShaderButtonActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout optionPanelLayout = new org.jdesktop.layout.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(optionPanelLayout.createSequentialGroup()
                .add(jLabel1)
                .add(20, 20, 20))
            .add(jSlider1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
            .add(optionPanelLayout.createSequentialGroup()
                .add(ShaderButton)
                .addContainerGap())
            .add(optionPanelLayout.createSequentialGroup()
                .add(jButton1)
                .addContainerGap())
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(optionPanelLayout.createSequentialGroup()
                .add(jLabel1)
                .add(8, 8, 8)
                .add(jSlider1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ShaderButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .add(93, 93, 93))
        );

        previewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview"));

        FileMenu.setText("File");

        OpenMenuItem.setText("Open Model...");
        OpenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(OpenMenuItem);

        openTextureMenuItem.setText("Open Texture...");
        openTextureMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTextureMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(openTextureMenuItem);

        Menu.add(FileMenu);

        jMenu2.setText("Edit");
        Menu.add(jMenu2);

        setJMenuBar(Menu);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(previewPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 245, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(optionPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(optionPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(previewPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void OpenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenMenuItemActionPerformed
    Preferences p = Preferences.userNodeForPackage(this.getClass());
    String dir = p.get("ModelDir", null);
    if (dir != null) {
        modelChooser.setCurrentDirectory(new File(dir));
    }
    int returnVal = modelChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File f = modelChooser.getSelectedFile();

        p.put("ModelDir", f.getParent());
        
        XImporter i;
        try {
            i = new XImporter(f.toURL());
            mp.setData(i.getModel());
        } catch (MalformedURLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}//GEN-LAST:event_OpenMenuItemActionPerformed

private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
// TODO add your handling code here:
    mp.setZoom(jSlider1.getValue());
}//GEN-LAST:event_jSlider1StateChanged

private void openTextureMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTextureMenuItemActionPerformed
// TODO add your handling code here:

    Preferences p = Preferences.userNodeForPackage(this.getClass());
    String dir = p.get("TextureDir", null);
    if (dir != null) {
        textureChooser.setCurrentDirectory(new File(dir));
    }
     int returnVal = textureChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File f = textureChooser.getSelectedFile();
        p.put("TextureDir", f.getParent());
        try{
            mp.setTexture(f.toURL());
        } catch (MalformedURLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}//GEN-LAST:event_openTextureMenuItemActionPerformed

private void ShaderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShaderButtonActionPerformed
// TODO add your handling code here:
vertexShaderEditor.setVisible(true);//GEN-LAST:event_ShaderButtonActionPerformed
fragmentShaderEditor.setVisible(true);
}

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

playerColor = JColorChooser.showDialog(//GEN-LAST:event_jButton1ActionPerformed
                     this,
                     "Choose Player Color",
                     playerColor);

}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem OpenMenuItem;
    private javax.swing.JButton ShaderButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JMenuItem openTextureMenuItem;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPanel previewPanel;
    // End of variables declaration//GEN-END:variables

}
